server:
  port: 8080
#  error:
#    whitelabel:
#      enabled: false
#  servlet:
#    context-path: /demo

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/demo?characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 1111

  servlet:
    multipart:
      max-file-size: 10GB # 파일 최대 크기 (예: 10GB)
      max-request-size: 10GB # 요청 최대 크기 (예: 10GB)

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    display-request-duration: true  # API 요청 지속 시간 표시 (m/s)
    defaultModelsExpandDepth: -1  # Schema 표시 여부 (기본값: 1 (표시))

pagehelper:
  autoDialect: true # DB 자동 감지
  closeConn: true # 페이지 처리 완료 시 Connection 자동 닫힘